// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4WARPuIEXEA4We5QT-eW4JX2OPlIyzK0',
    appId: '1:1026696809660:android:37f88912d49138564554b9',
    messagingSenderId: '1026696809660',
    projectId: 'apnaeats-41654',
    storageBucket: 'apnaeats-41654.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc9e8UhaCs-94FWsyj0ItrogtJLuIHW_I',
    appId: '1:1026696809660:ios:d2debf334a6146134554b9',
    messagingSenderId: '1026696809660',
    projectId: 'apnaeats-41654',
    storageBucket: 'apnaeats-41654.firebasestorage.app',
    androidClientId: '1026696809660-qccsgcktgcv8pll05p1mmgd9k5lqc233.apps.googleusercontent.com',
    iosClientId: '1026696809660-roamqn2jnm51cc8luu6qjmti5ga9ljnd.apps.googleusercontent.com',
    iosBundleId: 'com.apnaeats.fooduserAppDevMehedi',
  );

}